### ISSUE TITLE
Decompress Error: Unable to determine archive type

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#59]
Using the decompress plugin on the attached file...
[ses-manse.zip](https://github.com/PUNCH-Cyber/stoq-plugins-public/files/2974566/ses-manse.zip)

Results in..
```
stoq scan manse.zip -a mimetype decompress
[2019-03-16 18:48:31,835 ERROR] stoq: worker:failed to scan
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 653, in _single_scan
    worker_response = plugin.scan(payload, request_meta)  # pyre-ignore[16]
  File "/home/pass/.stoq/plugins/decompress/decompress.py", line 156, in scan
    f'Unable to determine archive type, mimetype: {mimetype}'
stoq.exceptions.StoqPluginException: Unable to determine archive type, mimetype: text/plain
{
    "results": [
        {
            "payload_id": "eb41f67a-d223-4d47-83db-d1f08d0a6756",
            "size": 853606,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {
                    "filename": "manse.zip"
                },
                "dispatch_to": []
            },
            "workers": [
                {
                    "mimetype": {
                        "mimetype": "application/zip"
                    },
                    "decompress": {}
                }
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    [
                        "mimetype",
                        "decompress"
                    ]
                ],
                "archivers": []
            },
            "extracted_from": null,
            "extracted_by": null
        },
        {
            "payload_id": "41f6c260-de53-4aba-bbd2-f086b79609c8",
            "size": 850868,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {
                    "filename": "MANSEFIT.PRG"
                },
                "dispatch_to": []
            },
            "workers": [
                {
                    "mimetype": {
                        "mimetype": "application/octet-stream"
                    },
                    "decompress": {}
                }
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    [
                        "mimetype",
                        "decompress"
                    ]
                ],
                "archivers": []
            },
            "extracted_from": "eb41f67a-d223-4d47-83db-d1f08d0a6756",
            "extracted_by": "decompress"
        },
        {
            "payload_id": "655f5ccc-1f22-468b-8cd7-2539a534e7ea",
            "size": 897,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {
                    "filename": "README.NOW"
                },
                "dispatch_to": []
            },
            "workers": [
                {
                    "mimetype": {
                        "mimetype": "application/octet-stream"
                    },
                    "decompress": {}
                }
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    [
                        "mimetype",
                        "decompress"
                    ]
                ],
                "archivers": []
            },
            "extracted_from": "eb41f67a-d223-4d47-83db-d1f08d0a6756",
            "extracted_by": "decompress"
        },
        {
            "payload_id": "d4eb6781-ec35-4a04-bf00-823e8177c803",
            "size": 3377,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {
                    "filename": "scene.org.txt"
                },
                "dispatch_to": []
            },
            "workers": [
                {
                    "mimetype": {
                        "mimetype": "text/plain"
                    }
                }
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    [
                        "mimetype",
                        "decompress"
                    ]
                ],
                "archivers": []
            },
            "extracted_from": "eb41f67a-d223-4d47-83db-d1f08d0a6756",
            "extracted_by": "decompress"
        }
    ],
    "request_meta": {
        "archive_payloads": true,
        "source": null,
        "extra_data": {}
    },
    "errors": {
        "decompress": [
            "worker:failed to scan: File \"/home/pass/.stoq/plugins/decompress/decompress.py\", line 156, in scan ; stoq.exceptions.StoqPluginException: Unable to determine archive type, mimetype: text/plain"
        ]
    },
    "time": "2019-03-16T18:48:31.837008",
    "decorators": {},
    "scan_id": "3cb2d161-f275-4cf8-aaf5-b77474de59d7"
}
```

Not quite clear what's happening. I first though it might be the file detected as an octet-stream (MANSEFIT.PRG ) is not a compressed file, but the mime type indicated in the error is text/plain.

**Comment by mlaferrera** [comment]
You're running stoq with `-a decompress`, which means even extracted payloads will be sent to the `decompress` plugin for extraction. You'll want to change your command to only send the initial payload (the zip file) to the decompress plugin. This can be done by changing your command to `stoq scan ses-manse.zip -a mimetype -s decompress`

**Comment by Kolano** [comment]
But I do want nested archives to be decompressed. The issue seems to be with the way files detected as octet-stream are handled, at least when the octet-streams are not compressed types.

**Comment by mlaferrera** [comment]
You'll want to use  dispatching then to automatically route compressed payloads to the `decompress` plugin. I would definitely not recommend sending every payload, be it compressed or not, to `decompress`.

**Comment by Kolano** [comment]
OK, I'm doing so but it's a bit irksome since the decompress plugin does it's own type checking.

Would be nice if decompress provided an option to override ARCHIVE_MAGIC / ARCHIVE_CMDS, or perhaps, since I guess arrays may be a pain in the current properties file format, just provide an option to specify an alternate command to be used /wo type checks.

Looks like one can perhaps bypass the ARCHIVE_MAGIC lookup at least by specifying "request_meta.extra_data.archiver", though that doesn't seem to be documented.

**Comment by mlaferrera** [comment]
I'm happy to accept a PR that would help to improve the functionality.

**Comment by mlaferrera** [comment]
Closed due to inactivity. Please feel free to reopen if needed.
